In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers
import tensorflow.keras.utils as ku 
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
from google.colab import files
import os
uploaded = files.upload()
all_files = [(name, os.path.getmtime(name)) for name in os.listdir()]
latest_file = sorted(all_files, key=lambda x: -x[1])[0][0]

Saving a.txt to a.txt


In [ ]:
lyric=open('a.txt').read()
lyric[:40]


' \n\nL-ungi\nKing khan\nYo yo honey singh\n\nM'

In [ ]:
corpus=lyric.lower().split('\n')
for i in range(40,60):
    print(corpus[i])

dont miss the chance

lungi dance, lungi dance
lungi dance, lungi dance
lungi dance, lungi dance, 
lungi dance, lungi dance - [2] 

night club me aaya main toh
mujhko rokega kaun aur kaiko
mera mood main dance karega
kisika daddy sai ni darega

jisko jo bhi hai karna woh karlo
idhar he main hoon khada pakadlo
ghar pe jaakar tum google karlo
mere baare me wikipedia pe padhlo

lungi dance, lungi dance, 
lungi dance, lungi dance
lungi dance, lungi dance, 


In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
total_words = len(tokenizer.word_index) + 1
total_words


710

In [ ]:
input_sequences = []
for line in corpus:
  token_list = tokenizer.texts_to_sequences([line])[0]
  print(token_list)
  for i in range(1, len(token_list)):
    n_gram_sequence = token_list[:i+1]
    input_sequences.append(n_gram_sequence)

[]
[]
[359, 360]
[191, 226]
[55, 55, 148, 149]
[]
[361, 43, 73, 192, 193]
[194, 44, 150, 151, 152, 44]
[195, 45, 362, 227, 44]
[34, 363, 196, 153, 197]
[]
[228, 43, 73, 192, 193]
[194, 44, 198, 151, 229]
[195, 230, 231, 232]
[233, 196, 153, 197]
[]
[85, 12, 74, 97]
[86, 98, 12, 99]
[85, 12, 74, 97]
[86, 98, 12, 99]
[234, 235, 236]
[]
[4, 3, 4, 3]
[4, 3, 4, 3]
[4, 3, 4, 3]
[4, 3, 4, 3, 46]
[]
[237, 75, 238, 239, 154, 240, 155]
[2, 156, 74, 241, 242, 154, 243, 155]
[237, 75, 238, 239, 154, 240, 155]
[2, 156, 74, 241, 242, 154, 243, 155]
[]
[364, 45, 157, 87, 365, 366]
[60, 12, 76, 367, 199]
[4, 43, 368, 199]
[369, 370, 371, 199, 46]
[]
[85, 12, 74, 97]
[86, 98, 12, 99]
[85, 12, 74, 97]
[86, 98, 12, 99]
[]
[4, 3, 4, 3]
[4, 3, 4, 3]
[4, 3, 4, 3]
[4, 3, 4, 3, 46]
[]
[100, 244, 45, 245, 2, 246]
[247, 372, 248, 29, 373]
[101, 153, 2, 3, 374]
[375, 102, 376, 23, 377]
[]
[378, 103, 35, 1, 379, 200, 249]
[126, 158, 2, 40, 380, 381]
[47, 31, 382, 383, 384, 249]
[13, 127, 45, 385, 31, 386]
[]
[4, 

In [ ]:
print(input_sequences)

[[359, 360], [191, 226], [55, 55], [55, 55, 148], [55, 55, 148, 149], [361, 43], [361, 43, 73], [361, 43, 73, 192], [361, 43, 73, 192, 193], [194, 44], [194, 44, 150], [194, 44, 150, 151], [194, 44, 150, 151, 152], [194, 44, 150, 151, 152, 44], [195, 45], [195, 45, 362], [195, 45, 362, 227], [195, 45, 362, 227, 44], [34, 363], [34, 363, 196], [34, 363, 196, 153], [34, 363, 196, 153, 197], [228, 43], [228, 43, 73], [228, 43, 73, 192], [228, 43, 73, 192, 193], [194, 44], [194, 44, 198], [194, 44, 198, 151], [194, 44, 198, 151, 229], [195, 230], [195, 230, 231], [195, 230, 231, 232], [233, 196], [233, 196, 153], [233, 196, 153, 197], [85, 12], [85, 12, 74], [85, 12, 74, 97], [86, 98], [86, 98, 12], [86, 98, 12, 99], [85, 12], [85, 12, 74], [85, 12, 74, 97], [86, 98], [86, 98, 12], [86, 98, 12, 99], [234, 235], [234, 235, 236], [4, 3], [4, 3, 4], [4, 3, 4, 3], [4, 3], [4, 3, 4], [4, 3, 4, 3], [4, 3], [4, 3, 4], [4, 3, 4, 3], [4, 3], [4, 3, 4], [4, 3, 4, 3], [4, 3, 4, 3, 46], [237, 75], [23

In [ ]:
max_sequence_len = max([len(x) for x in input_sequences])
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))
print(max_sequence_len)
print(input_sequences)

10
[[  0   0   0 ...   0 359 360]
 [  0   0   0 ...   0 191 226]
 [  0   0   0 ...   0  55  55]
 ...
 [  0   0   0 ...  32  54  32]
 [  0   0   0 ...   0   9  33]
 [  0   0   0 ...   9  33 147]]


In [ ]:
model = Sequential() 
model.add(Embedding(710, 160,input_length=max_sequence_len-1))
model.add(Bidirectional(LSTM(200, return_sequences = True)))
model.add(Dropout(0.2))
model.add(LSTM(100)) 
model.add(Dense(710/2, activation='relu', kernel_regularizer=regularizers.l2(0.001))) 
model.add(Dense(710, activation='softmax')) 
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy']) 
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 9, 160)            113600    
_________________________________________________________________
bidirectional_1 (Bidirection (None, 9, 400)            577600    
_________________________________________________________________
dropout_1 (Dropout)          (None, 9, 400)            0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 100)               200400    
_________________________________________________________________
dense_2 (Dense)              (None, 355)               35855     
_________________________________________________________________
dense_3 (Dense)              (None, 710)               252760    
Total params: 1,180,215
Trainable params: 1,180,215
Non-trainable params: 0
____________________________________________

In [ ]:
predictors, label = input_sequences[:,:-1],input_sequences[:,-1]
label = ku.to_categorical(label, num_classes=total_words)
history = model.fit(predictors, label, epochs=50, verbose=1)

Epoch 1/50
66/66 [==============================] - 5s 68ms/step - loss: 6.3577 - accuracy: 0.0181
Epoch 2/50
66/66 [==============================] - 5s 69ms/step - loss: 5.7607 - accuracy: 0.0305
Epoch 3/50
66/66 [==============================] - 5s 69ms/step - loss: 5.4599 - accuracy: 0.0366
Epoch 4/50
66/66 [==============================] - 5s 69ms/step - loss: 5.2043 - accuracy: 0.0476
Epoch 5/50
66/66 [==============================] - 5s 70ms/step - loss: 4.9629 - accuracy: 0.0571
Epoch 6/50
66/66 [==============================] - 5s 69ms/step - loss: 4.7175 - accuracy: 0.0876
Epoch 7/50
66/66 [==============================] - 5s 68ms/step - loss: 4.4352 - accuracy: 0.1171
Epoch 8/50
66/66 [==============================] - 5s 68ms/step - loss: 4.2001 - accuracy: 0.1409
Epoch 9/50
66/66 [==============================] - 5s 69ms/step - loss: 3.9442 - accuracy: 0.1771
Epoch 10/50
66/66 [==============================] - 5s 69ms/step - loss: 3.6682 - accuracy: 0.2085
Epoch 11/

In [ ]:
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("TaylorSwiftModel.h5")
print("Saved model to disk")

Saved model to disk


In [ ]:
next_words = 30
seed_text = "Yo Yo Honey Singh"
for _ in range(next_words):
	token_list = tokenizer.texts_to_sequences([seed_text])[0]
	token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
	predicted = model.predict_classes(token_list, verbose=0)
	output_word = ""
	for word, index in tokenizer.word_index.items():
		if index == predicted:
			output_word = word
			break
	seed_text += " " + output_word
print(seed_text)

Yo Yo Honey Singh haal ni kad de 2 de kundi kundi se maana tujhe ek vaar ae ae tujhe ek vaar tujhe ek vaar tujhe ek vaar ae ae ae ae ae ae


In [ ]:
input_sequences[:,-1]

array([58,  3, 86, ..., 21,  5,  1], dtype=int32)

In [ ]:
input_sequences[:,:-1]

array([[  0,   0,   0, ...,   0,   0,  61],
       [  0,   0,   0, ...,   0,  61,  58],
       [  0,   0,   0, ...,  61,  58,   3],
       ...,
       [  0,   0,   0, ...,   2, 118, 153],
       [  0,   0,   0, ..., 118, 153,  21],
       [  0,   0,   0, ..., 153,  21,   5]], dtype=int32)